### PR TITLE
Yzhbankov/T-1

### PR DESCRIPTION
**Pull request by nesterone**

### CODE REVIEW

**Comment by nesterone** [comment]
@yzhbankov  plz, remove .idea/ and add it to .gitignore

**Comment by nesterone** [comment]
Issues with dev testing in a project root

```
➜  zorko-platform git:(nesterone/t-4) ✗ docker-compose up
Creating network "zorko-platform_default" with the default driver
Creating volume "zorko-platform_mysql_data" with local driver
Pulling mysql (mysql:5.7)...
5.7: Pulling from library/mysql
bf5952930446: Pull complete
8254623a9871: Pull complete
938e3e06dac4: Pull complete
ea28ebf28884: Pull complete
f3cef38785c2: Pull complete
894f9792565a: Pull complete
1d8a57523420: Pull complete
5f09bf1d31c1: Pull complete
1b6ff254abe7: Pull complete
74310a0bf42d: Pull complete
d398726627fd: Pull complete
Digest: sha256:da58f943b94721d46e87d5de208dc07302a8b13e638cd1d24285d222376d6d84
Status: Downloaded newer image for mysql:5.7
Pulling keycloak (quay.io/keycloak/keycloak:latest)...
latest: Pulling from keycloak/keycloak
Digest: sha256:dc9c72ec3a8ac1f8edf557219eda8d0d801051f5a613e2383b83326423f80618
Status: Downloaded newer image for quay.io/keycloak/keycloak:latest
Pulling sso-gateway (yzhbankov/sso-gateway:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling sso-gateway (yzhbankov/sso-gateway:latest)...
ERROR: pull access denied for yzhbankov/sso-gateway, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
➜  zorko-platform git:(yzhbankov/T-1) ✗ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: nesterone
Password: 
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
➜  zorko-platform git:(yzhbankov/T-1) ✗ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: nesterone
Password: 
Login Succeeded
➜  zorko-platform git:(yzhbankov/T-1) ✗ docker-compose up
Pulling sso-gateway (yzhbankov/sso-gateway:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling sso-gateway (yzhbankov/sso-gateway:latest)...
ERROR: pull access denied for yzhbankov/sso-gateway, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
➜  zorko-platform git:(yzhbankov/T-1) ✗ 

```

**Comment by yzhbankov** [comment]
before the running docker-compose up you should build the yzhbankov/sso-gateway image running the command:
"docker build -t yzhbankov/sso-gateway ."

**Comment by nesterone** [comment]
Thx!

Checked out updates, followed steps till the `npm i` in client folder. Got next issue 

```
➜  client git:(yzhbankov/T-1) ✗ npm i              

> fsevents@1.2.13 install /projects/zorko-io/zorko-platform/apps/sso-gateway/client/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'nan'
Require stack:
- /projects/zorko-io/zorko-platform/apps/sso-gateway/client/node_modules/watchpack-chokidar2/node_modules/fsevents/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:123:20)
    at Object.runInThisContext (vm.js:313:38)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at evalScript (internal/process/execution.js:79:25)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/nesterone/.nvm/versions/node/v12.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/nesterone/.nvm/versions/node/v12.1.0/bin/node" "/Users/nesterone/.nvm/versions/node/v12.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /projects/zorko-io/zorko-platform/apps/sso-gateway/client/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> fsevents@1.2.13 install /projects/zorko-io/zorko-platform/apps/sso-gateway/client/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'nan'
Require stack:
- /projects/zorko-io/zorko-platform/apps/sso-gateway/client/node_modules/webpack-dev-server/node_modules/fsevents/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:123:20)
    at Object.runInThisContext (vm.js:313:38)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at evalScript (internal/process/execution.js:79:25)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/nesterone/.nvm/versions/node/v12.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/nesterone/.nvm/versions/node/v12.1.0/bin/node" "/Users/nesterone/.nvm/versions/node/v12.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /projects/zorko-io/zorko-platform/apps/sso-gateway/client/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> core-js@2.6.11 postinstall /projects/zorko-io/zorko-platform/apps/sso-gateway/client/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

npm WARN sso-client@1.0.0 No description
npm WARN sso-client@1.0.0 No repository field.

added 827 packages from 416 contributors and audited 827 packages in 15.13s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
➜  client git:(yzhbankov/T-1) ✗ 
```

**Comment by yzhbankov** [comment]
please try a fix

**Comment by nesterone** [comment]
Able to test client with keycloak,  it works, great job!

Let's decide on what to do next. Plz, review my proposal 

To close #1, I propose to extend that PR with steps for backend API, I've tried to run it but it fails, maybe I'm doing something wrong. Having working backend we can close current PR and move to the next steps in Auth/Keycloack investigation

For the next steps, I can prep tasks for: 

- Login Theme Customization
- Integration with Github auth provider  
- Investigate Automate keycloack configuration by creation realms, clients and default user/users (aka script or proper docker config)

@yzhbankov  What do you think?

**Comment by yzhbankov** [comment]
> Able to test client with keycloak, it works, great job!
> 
> Let's decide on what to do next. Plz, review my proposal
> 
> To close #1, I propose to extend that PR with steps for backend API, I've tried to run it but it fails, maybe I'm doing something wrong. Having working backend we can close current PR and move to the next steps in Auth/Keycloack investigation
> 
> For the next steps, I can prep tasks for:
> 
> * Login Theme Customization
> * Integration with Github auth provider
> * Investigate Automate keycloack configuration by creation realms, clients and default user/users (aka script or proper docker config)
> 
> @yzhbankov What do you think?

Yes, this is a great idea. Also, I would like to propose extending the UI with user management (CRUD) that should includes the role management. Also need to think about how to integrate a couple of clients with the users that have access to both of them and only to one. The server side should be extended with some basic/example API (protected, not protected, protected by )

**Comment by nesterone** [comment]
> Yes, this is a great idea. Also, I would like to propose extending the UI with user management (CRUD) that should include the role management. 

Correct me if I'm wrong but all those operations we can do withing Keycloack Admin UI. 
Actually it's one of my ideas behind choosing Keycloak, to leverage not only it's Login UI but to re-use it's admin UI to manage users/roles, permission, and organization.

> Also need to think about how to integrate a couple of clients with the users that have access to both of them and only to one.

We are going to have at least two web clients `web-portal` and `vega-editor`. In the near future, I don't see a use case to have different user access between them.

> The server side should be extended with some basic/example API (protected, not protected, protected by )

Yep, we definitely need it

**Comment by nesterone** [comment]
@yzhbankov , I've prepared few issues 

#10, #9 and #8  for future research.

For the current one, ping me with any updates about server-side integration with Keycloack

**Comment by yzhbankov** [comment]
@nesterone Hi, could you try to start the project? I had added the users by default on the project start. The configuration commonly should work but requires some cleaning.

**Comment by nesterone** [comment]
@yzhbankov , thx!

Checked changes,  cool it works, closing #10

**Comment by nesterone** [comment]
So, to merge this PR in `master` we only need a working  example of API backend with keycloak

**Pull request merged**
