### PR TITLE
Whiteadam2/gh 65

### PR DESCRIPTION
**Pull request by whiteadam2**

### CODE REVIEW

**Comment by nesterone** [comment]
features/examples/components/ExamplePage.jsx

**Comment by nesterone** [comment]
you no need to move `layout` folder to examples feature, leave them in `components` folder

**Comment by nesterone** [comment]
Just reviewed the code and it looks much better now.

**Comment by nesterone** [comment]
Plz, move `ApiExample.jsx` and `ValidatorExample.jsx`
to examples/components and integrate on example page

remove empty `features/example` folder

move ExamplesPage.jsx to `features/examples/components`

**Comment by whiteadam2** [comment]
> remove empty `features/example` folder

there are no empry features/example folder, but we have empty lib/common (after moving ApiExample and ValidatorExample). I've removed lib/common

**Comment by whiteadam2** [comment]
What sholud I use like prop types and default props of props.children? Ive found these solutions:
` PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.node), PropTypes.node])` for prop types
and `children: null ` for default props
Is it correct?

**Comment by whiteadam2** [comment]
I've added Router for Example components. But it wont work. Check please!

**Comment by nesterone** [comment]
yep, checking

**Review by nesterone — APPROVED** [review]

**Pull request merged**
