### PR TITLE
gh-60. Fix styles loading in production build

### PR DESCRIPTION
**Pull request by yzhbankov**
close #gh-60

### CODE REVIEW

**Comment by nesterone** [comment]
strange just checked out and it still renders without CSS

**Comment by yzhbankov** [comment]
@nesterone could you please provide the result of the web-portal-client build (build folder content)? thx

**Comment by nesterone** [comment]
```
 tree .
.
├── client.min.js
├── index.html
├── styles.chunk.js
└── vendors~app.chunk.js

0 directories, 4 files

```


Zorko 2020-12-07 23-57-57

**Comment by yzhbankov** [comment]
@nesterone please try now

**Review by nesterone — APPROVED** [review]

**Pull request merged**
