### PR TITLE
gh-23 Add static index and login pages

### PR DESCRIPTION
**Pull request by whiteadam2**
- Add index file from tailwindua template
- Add login file from tailwindua template

### CODE REVIEW

**Comment by nesterone** [comment]
I've merged #28, so you have to update from 'dev' and move your code to react component, plz remove all files created in `web-portal` and add `web-portal-client/src/LoginPage.jsx` move your code in LoginPage component, then integrate that component in `index.jsx`

**Comment by whiteadam2** [comment]
Ive completed. Have 2 questions:
1. I suppose you commented out Yariks hierarchy of routs. i'm just replace main component to login page but I think its useless
2. I dont know why without extentions it wont work 
import LoginPage from "./LoginPage.jsx"

**Comment by nesterone** [comment]
@whiteadam2 

After changes from @whiteadam2  and me, you have to resolve conflicts 

Be aware, that I've to rename `src` to `lib` in `web-portal-client`, after you would resolve conflicts, I suggest to 

got to root of the project and run `yarn reset`, more info about [project tools](https://github.com/zorko-io/zorko-platform/blob/dev/CONTRIBUTING.md#project-tools) 


Also, read [PR process](https://github.com/zorko-io/zorko-platform/blob/dev/CONTRIBUTING.md#pull-request-process), to prepare code for review

**Comment by nesterone** [comment]
> Ive completed. Have 2 questions:
> 
> 1. I suppose you commented out Yariks hierarchy of routs. i'm just replace main component to login page but I think its useless

It's not ok, better is to mount your component to react-router with URL like 'login', right now it's in `ApplicatinoContainer` component

> 2. I dont know why without extentions it wont work
>    import LoginPage from "./LoginPage.jsx"
It's because the `import` syntax doesn't restrict us to specify an extension for imports. Actually, it gives us flexibility in the long run, so I no need to change all files linked to my file when for some reason I have to change the extension

**Comment by whiteadam2** [comment]
done

**Pull request merged**
